server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersvcdb
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: USER-SERVICE


