server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersvcdb
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: USER-SERVICE

resilience4j:
  circuitbreaker:
    instances:
      userBorrowInformation:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

